# Generated by Django 3.2 on 2021-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hazard_ghs',
            options={'managed': True, 'verbose_name': 'Уведомление GHS связанное с веществом', 'verbose_name_plural': 'Уведомления GHS связанные с веществами'},
        ),
    ]
