# Generated by Django 3.2 on 2021-10-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hazard',
            options={'managed': True, 'verbose_name': 'Card of hazard', 'verbose_name_plural': 'Cards of hazard'},
        ),
        migrations.AlterModelOptions(
            name='hazard_ghs',
            options={'managed': True, 'verbose_name': 'GHS notification related with ingredient', 'verbose_name_plural': 'GHS notifications related with ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'managed': True, 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
    ]
