from image_to_text.text_postprocessing import TextPostprocessing
import time

new_dataset = ['AL ALA Mae a Todi ardor vu TTTN\nEr sais Ton oe SE Aa TT i\nROT OL, ISOPROPYL MYRISTATE. CAFFEINE. AMMOMLM ACRYLOYLOME WY Ike\noy 2 A ETHER, FUCUS VESICULOBUS EXTRACT. CENTELLA ASWATICA fo\nCROTON LECHLER! (SANGRE DE DRAGON RESIN EXTRACT ALUMINUM SUCROSE (C1\nPTT Ley ee Me I TY WT py ereaptoriyan\nCQUEUS FORSKOHLIl (INOWAN COLIRUB) ADOT EXTRACT, PMENDXYETHANOL NEM\nLY ag x er]\nAT aT ro TE\n\ni a oo a Say oo AFC\n\x0c',
               'G xnan/wypamui; Paraffinum\ni ide, Dicaprytyl Ether,\ncapratq Isopropyl Stearate, Butyl Met i |\nsia Chanensis Seed Oil, Tocopheryl Acetate, |\nButyiphenyl Methylpropional, Benzyl Alcohel,\nCitroneliol, Eugenol, Coumnarin, Parfum.\nAAny ONAND gem. ED ERRPES.Ya\n\x0c',
               'EIPEBERRILNE £TrVLHEXYL PALMITATE. GLYCERIN ROR ao\nBE POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, HYDROXYETHYLAC-\nJRYLATE / SOOIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER. XYUITYLGLU-\n* COSIDE. ANHYDROXYLITOL. XYLITOL, BEHENYL ALCOHOL. CETYL ALCOHOL!\n\\SOSTEARYL ISOSTEARATE. POTASSIUM CETYL PHOSPHATE CETYL BEHEN-\nATE. BEHENIC ACID. BETAINE, PPG-15 STEARYL ETHER TITANIUM DIOXIDE\nALUMINA. SIMETHICONE, BUTYLENE GLYCOL. 10-HYDROXYDECANOIC ACID.\nSEBACIC ACID. 1.10-DECANEDIOL OIMETHICONENVINYL OMETHICONE\nCROSSPOLYMER, SILICA, LITCHI CHINENSIS PERICARP EXTRACT. AQUA (GLA-\nCIER WATER), ALLANTOIN, PARFUM (FRAGRANCE). METHYLPARABEN. 1SO-\n> MYRISTATE. TRITICUM VULGARE (WHEAT) GERM OIL, TOCOPHERYL\nBHT, PROPYLPARABEN, 2-8BROMO-2-NITROPROPANE-1,3-DI0L, BU-\nMETHYLPROPIONAL, CITRONELLOL, GERANIOL. HEXYL C=\nae vasanaaTVDE 18 1eors 5 ‘C1 He soe 25 °C |\n\x0c',
               'СКЛАД: ВОДА ОЛЯ МІНЕРАЛЬНА, КАОЛІН, ГЛІЦЕРИЛ / МОНОСТЕАААТ,\nкод а Ло дана с М і о ММ пін\nЕКСТРАКТ ЧИСТОТІЛУ, ОЛІЯ ГРЕЦЬМОГО ГОРССУ. ГЛІЦЕРИН, УРЕА, ЦЕТЕАРИЛО-\nОЛЯ ЯЛИЦІ, КАМФОРА, ЕФІРНА ОЛІЯ ЧАЙНОГО ДЕРЕВА АРОМАТИЧНА\nКОМПОЗИЦІЯ, ПРОПІЛЕНГЛІКОЛЬ, БЕНЗОАТ НАТРІЮ,\n\nФЕНОКСЕТАНОЛ, КАПРИЛІЛГЛІКЮОЛЬ, БЕНЗИЯ САЛІЦИ-\n\nЛАТ. ЦИТРОНЕЛЛОЛ, ГЕКСИЛ ЦИННАМАЯ, ГІДРОМСИ- плин\nЛІМОНЕН,. ПДРОЮСИІЗОГЕИСИЛ. З-ДИКЛОГЕИСЕНКАРЬО-\nкн вБ5-3\n\x0c',
               'EE BRE SL a Ld\nCOCTAB/INGREDIENTS: AQUA (WATER), ALUMINUM CHLOROHYDRATE, PPG-3\nBENZYL ETHER MYRISTATE, CETYL ALCOHOL, GLYCERYL STEARATE, PEG-T5 STEA-\nRATE, CETETH-20, STEARETH-20, PPG-15 STEARYL ETHER, CYCLOPENTASILOXANE,\nDIMETHICONE CROSSPOLYMER, SYNTHETIC BEESWAX, DIMETHICONE, BEHENYL AL-\nCOHOL, TAPIOCA STARCH, POLYMETHYLSILSESQUIOXANE, STEARYL DIMETHICONE,\nOCTADECENE, POLYACRYLATE CROSSPOLYMER-6, PARFUM (FRAGRANCE), PHE-\nNOXYETHANOL, METHYLPARABEN, ETHYLPARABEN, PROPYLPARABEN, ISOPROPYL\nMYRISTATE, TRITICUM VULGARE (WHEAT) GERM OIL, TOCOPHERYL ACETATE, BHT,\nPENTHYLENE GLYCOL, PEG-40 HYDROGENATED CASTOR ON, TRIDECETH-9, BISAB-\nOLOL ROSA DAMASCENA FLOWER EXTRACT, BUTYLPHENYL METHYLPROPIONAL, LI-\nne RY a hE Twa\n[PREP Sh a NTR TT TH ITIT-) b14 ‘C\n\x0c',
               'Cocrae (Ingredients): Aqua (Water), Hydroxyethyl Uree,\nel ill upto)\nA Ci Hyaluronate, 23, Carbomer,\nXanthan Gum, Parfum (| i" Elastin, Soluble }\nHyaluronic Acid, Lactic rv . Urea, Sorbitol, Ti\nGlycol Serine, Rosa Damascena (Rose)\nDamascena (Rose) Oil, Sodwm Chioride, Sodium\nFV PY Eg Te mY Phencxyethand x\nEe Propyiparaben EE\n\n1,3-Oiot, C1 19140 (FOAC Yellow No. 5), CI 42090\nfFoaC Blue No. 1)\n\nMaroTosuTens;\n\x0c',
               'Cocras/ingredients (INCI): Aqua, Glycerin, Glyosy\nStearate, Dicaprylyl Ether, Isopropy! Myristate,\nCetearyl Alcohol, Olea Europaea (Olive) Fruit Oi\nCeresin, Ceteareth-23, Dimethicone, Cetearsth-2)\nCeteareth-12, Cetyl Palmitate, Butylene Glycol, Sra\nSecretion Filtrate, Panthenol, Sodium Polyacrya\n"afm, Sodium Hyaluronate, Methylparaben, |\n“0pylparaben, Phenoxyethanol, Ethyl Hexared?”\n\x0c',
               "Спад: Резма лива ( / 2.5 Ж). рисове борошно, вода питна. крохмаль т; -\nсіль кухонна; Ск Фо-бо (24.65). вода питна, сіль коне, олія. пальмова; супемі,\nпидсилюваче смаку та аромату: Е621. Е635. чукор, яловичий жир сушений, імбир провод,\nтатюковий модифікований, мальтолектрин. ароматизатори. овочева сумні (полка,\nкукурудза, картопля, батат), м'ясо куряче сушене порошок (0.66). перець чорний мелений, регулжкор\nкислотності. сукцинат натрію. кореанлр мелений, кориця мелена, кардамон мелений, ані, барвники.\nцукровий колер, куркучін;. підсолоджувач. гспартам. Овочі сушені (2996): морква сушена. цибуа\nзелена сушена (15,85), коріандр. пшеничний текстурат (борошно пшеничне, палзачий би,\nрегулятор кислотност Е4500і). стабілізатор. карбонат натрию. бареник. мукровий кодер,\nантиоксидант ЕЗ06) Продукт може мітити чезначну кількість селери, с, продукта переробки\n\x0c",
               'COCTAB (WNGREDIENTS): AQUA (WATER), ALCOHOL, POLYVINYL ALLOHOL\nGLYCERIN, PVP, XANTHAN GUM, SYNTHETIC FLUORPHLOGOPITE, TITANILW\nDIONIDE, PARFUM (FRAGRANCE), METHYLPROPANEDIOL, POLYSORBATE 80\nLEPTOSPERMONE, SALICYUC ACID, ISOLEPTOSPERMONE, FLAVESONE, SALIX\nALBA (WILLOW) BARK EXTRACT, ALLANTOIN, C! 77460 (IRON QNGDES).\nPROPANEDIOL, SODIUM CITRATE, C1 77820 {COLLOIDAL SILVERY\n\x0c',
               'IL Ah 2 Maen aft\nCOCTAB/INGREDIENTS: AQUA (WATER), ALUMINUM CHLOROHYDRATE, PPG-3\nBENZYL ETHER MYRISTATE, CETYL ALCOHOL, GLYCERYL STEARATE, PEG-75 STEA-\nRATE, CETETH-20, STEARETH-20, PPG-15 STEARYL ETHER, CYCLOPENTASILOXANE,\nDIMETHICONE CROSSPOLYMER, SYNTHETIC BEESWAX, DIMETHICONE, BEHENYL AL-\nCOHOL. TAPIOCA STARCH, POLYMETHYLSILSESQUIOXANE, STEARYL DIMETHICONE,\nOCTADECENE, POLYACRYLATE CROSSPOLYMER-6, PARFUM (FRAGRANCE), PHE-\nNOXYETHANOL, METHYLPARABEN, ETHYLPARABEN. PROPYLPARABEN, ISOPROPYL\nMYRISTATE, TRITICUM VULGARE (WHEAT) GERM OIL, TOCOPHERYL ACETATE, BHT,\nPENTHYLENE GLYCOL, PEG-40 HYDROGENATED CASTOR OR, TRIDECETH-§, BISAB-\nOLOL. ROSA DAMASCENA FLOWER EXTRACT, BUTYLPHENYL METHYLPROPIONAL, LI\nMONENE, METHYL 2-OCTYNOATE I I.\n\x0c',
               'щини и\nДн А пси ей\n| / каприк тригліцериди. ді\n| читану, пропіленгліколь. ЛЕГО 52\n, бутилметоксидибензс":\nер и ВТ ев\n" ІВ\nщі ЗВ Я  м\nефір диметилсилан, матил-\nпод ж й\nрик ши; ШИ\nДМ на Ноні\n» ЕДТА, перфумерна шоо-\nет й\nІ. сі омана Та\n» чи"\n\x0c',
               'Cocrae EW Aid aH Water), Alcohol, Polyvinyl\n\nAlcohol, Glycerin, PVP, Cl 77481 {Iron oxides), CI 77891 Yes\n\nnium dioxide), Mica, PEG-12 Dsmethicone, Xanthan Gum,\n\nAl Ey rte Fr\nroleuca extract,\n\nDecapepude-21, Pd abn anand y.\n\n[CR , Oligopeplide-78, N\n\x0c',
               'A OS ASE NI, OMAA TARA Ra, RA. ittrd-trita ot E — SRAZŢ =\n\nCKNAJVCLCTABKW/SASTOJCI: Giycerin, PEG-8, Hydrated Sikca, Pentasodium Trphoapi\nSodium Laury! Sulfate, Aroma, Titanium Dioxide, Carbomer, CO\nStannous Fluonde, Cocamidopropy! Betaine, Sodium Saccharin, Lat\nSodium Fluoride, Limonene. MicTuTL prropua anosa 0.454 %, | . pt\n\x0c',
               'hLUAR Ahdhbiabdie aun tSNIL A NARS JR\nCOCTABANGREDIENTS: C\nTHCONE CROSSPOLYMER, E\nINSTT MINE\nHOC IR TE, PA\n\x0c',
               'ERTL ee ea eT Re To TTT\n1AR =¥JROXYPROPYLTRIMONIUM CHLORIDE, POLYOUMTEIGAS-11, NES\nCREEL TAIN (OR ol TW 13 To a" Wl 30\n4 UARABEN. PROPYLPARABEN, PARFUM (FRAGRANCE), SLX ASI AIK\nSEL (CNTY Tes: al Be IT gc: TY TY\nERR, SARE To: (Ta Veo Wo To ed\nRERSRES 4 (Rol Y VIVRE Vo 0°\n\x0c',
               'Mh abd ttdi an P Eliade on Jd add Sa BLA dA Rd dd. 1] >\nCOCTAB/INGREDIENTS: AQUA (WATER), SODIUM\nSULFATE, COCAMIDOPROPYL BETAINE, XANTHAN\n40 HYDROGENATED CASTOR OIL, PARFUM\nCHAMOMILLA RECUTITA EXTRACT, ALLANTON,\n2-BROMO-2-NITROPROPANE-1,3-DIOL, CI 19140\nLOW NO. 5), COUMARIN. 3\n\nCTT a TRI Tre pr varrgreees 5 oT TY\n\x0c'
               ]

# TODO прикрутить яязыковые профили и метод задания наборов ключевых слов под конкретный язык

d = 'WWWWWWWWWW INGREDIENTS: UNBLEACHED ENRICHED FLOUR\n(WHEAT FLOUR, MALTED BARLEY FLOUR, NIACIN.\nIRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC\nACID), WATER, YEAST, SOYBEAN OIL, CONTAINS\n2% OR LESS OF THE FOLLOWING: WHEAT GLUTEN,\nSALT, CALCIUM PROPIONATE (PRESERVATIVE),\nMALTED BARLEY EXTRACT, DATEM, ENZYMES. |\nCONTAINS: WHEAT,\nDistributed by JRO]; (o\nBatavia, IL 60510\nf—\n\x0c'
e =  'Ingredients: Aimonds, Seasoning\n(Maltodextrin, Salt, Sugar, Monosodium\nGlutamate, Roast Favor [Maltodextrin,\nNatural Flavor, Autolyzed Yeast Extract,\nModified Food Starch, Com Syrup Solids,\nLie RTT RSE ANE\nOnion Powder, Autolyzed Yeast Extract,\n(Sl oR TT CORR\n\x0c'
g = 'WIEHREINE\nAQUA (WATER) + CYCLOPENTASILOXANE * CETYL ALCO-\nJANES CTV a oa) AV RoR\nISOPROPYL LAUROYL SARCOSINATE METHYL GLUCETH-10e\nDIMETHICONE « POLYMETHYLSILSESQUIOXANE  RAFFINO-\nSE » SORBETH-40 TETRAOLEATE « BUTYLENE GLYCOL * PAR-\nFUM (FRAGRANCE) « POLYSORBATE 60 « METHYLPARA-\nBENHYDROXYETHYLCELLULOSE * CHLORPHENESIN * MA-\nGNESIUM CHLORIDE * SODIUM CITRATE * SORBITAN\nSTEARATE * DIMETHICONE/VINYL DIMETHICONE CROSSPOLY-\nMER « BHT GLYCERYL STEARATE * PROPYLPARABEN »\nCIN{Q iL Ne TL NRE ES ATH A\nDROLYZED CONCHIOLIN PROTEIN WZ2\n\x0c'
h = 'Stonedaked Pizza Base [Fortified Wheat Flour [Wheat Flour, Calc {Carbonate Tro,\nNiacin [83], Thiamin (B1)], Water, Rapeseed Gil, Salt, Yeast, Dextronel, Seasoned\nTomato Sauce (21%) Tomatoes, Tomato Puree, Corntlour, Sugar, Aadity Regulator\n[Citric Acid), Dried Oregano, Black Pepper, Garlk Powder |, Mozzarella Cheese\n{from Milk) (184), Fajita Chicken 112%] [Chicken Breast 87%), Water. Rapeseed Ol,\nMaltodextrin, Sugar, Salt, Rusk [Fortiied Wheat Flour {Wheat Flour,\nCalcrum Carbonate, Iron, Niacin [B3). Thiamin {B1]], Salt, Raising Agent\n{Ammonium Carbonates]), Spices Paprika, Cayenne Pepper, Cumin, White Pepper.\nBlack Pepper]. Lemon Juice from Concentrate, Modified Maize Starch, Garlic Powder,\nBirds Eye Chil Powder, Fortified Wheat Flour [Wheat Flour, Calcium Carbonate, Iron,\nNiacin a) Thiamin [B81]. Herbs {Oregano, Thyme, Parsley), Chilli Powder, Spice\nExtracts [Paprika Extract, Chilli Extract], Flavouring, Barley Malt Extract],\nSGOT A Red Peppers 16.0%). Allergy Advice! for allergens, including\ncereals containing gluten, see ingredients in bold.\nNO ARTIFICIAL COLOURS, FLAVOURS OR HYDROGENATED FAT.\n\x0c'

ae = 'LULY THE WRIGLEY COMPANY LTD., PLYMOUTH PL6 7PR.\nG03 WRIGLEY IRELAND LTD. PO BOX 11578, DUBLIN 17.\nCHEWY CANDIES IN A CRISP SUGAR SHELL WITH FRUIT FLAVOURS.\nINGREDIENTS: SUGAR, GLUCOSE SYRUP. PALM FAT, CITRIC ACID.\nMALIC ACID, DEXTRIN. MALTODEXTRIN, FLAVOURINGS, MODIFED\nNYE RE LTE (UY RET eT Te E10.\n£100, E171, E132. E1608, E133; TY UE 704\nEMULSIFIER POLYGLYCEROL ESTERS OF FATTY ACIDS.\nTRE AR LER haar\noR wort ov CONFECTIONS CR. KOM. Ye MEY 320, |\n\x0c'
be = 'Ingredients: Wheatlour, Vegstable OF\nHh ps ALES. Cheese 3 Sms\nYer\nAcidty Regulators (E262, E331), Acstic Acid\nnd rey\nSwestcom, Chives, Preservative (E220)\npod FB -%\n\x0c'
fe = "Da tas\ncia EI ACS A Ll\nDt DE GLUCOSE, GRAISSE DE\nPara a tans\nDar IA is\nCOLORANTS El62, El60a, El53, E132: CORRECTEUR\nD'ACIDITE CITRATE TRISODIQUE, AGENT D'ENROBAGE CIRE\nDE CARNAUBA, EMULSIFIANT LECITHINE, CONCENTRES\n(DE PATATE DQUCE, DE RADIS). CONSERVER AU FRAIS ET\nNJ SEC. A CONSOMMER DE PREFERENCE AVANT LE:\nVOR EN DESSOUS.\n\x0c"
ie = 'INGREDIENTS: WATER (75%), SUGARS (12%) (GLUCOSE (48%),\nFRUCTOSE (40%), SUCROSE (2%), MALTOSE (<1%]), STARCH\nAN AL OR ROI oN RE)\nASPARTIC ACID (16%), HISTIDINE (11%), LEUCINE (7%), LYSINE\n(5%), PHENYLALANINE (4%), ARGININE (4%), VALINE (4%),\nALANINE (4%), SERINE (4%), GLYCINE (3%), THREONINE (3%),\nISOLEUCINE (3%), PROLINE (3%), TRYPTOPHAN (1%), CYSTINE\n{1%), TYROSINE (1%), METHIONINE (1%), FATTY ACIDS (1%)\n{PALMITIC ACID (30%), OMEGA-6 FATTY ACID: LINOLEIC ACID\n{14%), OMEGA-3 FATTY ACID: LINOLENIC ACID (8%), OLEIC ACID\n{7%), PALMITOLEIC ACID (3%), STEARIC ACID (2%), LAURIC ACID\nA CS eR Ae Lo EE TE\nPHYTOSTEROLS, E515, OXALIC ACID, E300, E306\n(TOCOPHEROL), PHYLLOQUINONE, THIAMIN, COLOURS\n(YELLOW-ORANGE E101 (RIBOFLAVIN), YELLOW-BROWN E160),\nFLAVOURS (3-METHYLBUT-1-YL ETHANOATE, 2-METHYLBUTYL\nETHANOATE. 2.METHYL PROPAN-1-0l 3-METHYLBUTYL-1.0L 2-\n\x0c'
je = 'Potato Starch,Maltodextrin,Palm Oil,Salt,Wheat Flour (with added Calcium, Iron, Niacin, Thiamin),Colour (E15c),Sugar,Flavourings (contain Barley),Flavour Enhancers (E621, E635),Emulsifier (E322),(contains Soya)'
ke = 'Young Coconut Juice (80),Water,Sugar,Young Coconut Pulp,Citric Acid (E330),as Acidity Regulators,Potassium Metabisulphite (E224),as preservative.'
le = 'Peanuts 22%,Green Peas 20%,Wheat Flour 16%,Broad Beans 15%,Chick Peans 10%,Palm Olein 4%,Glultinous Rice 3%,Sugar 3%,Iodine Salt 2%,Seasoning Powder (Milk Protine ,Soy Bean),1.5%,Garlic 1%,Sesame Seed 1%,Chili Powder 0.5%,Egg 0.5%,Pepper 0.5%,Flavour Enhancer E621,E631,E635,Food Coloring E100,E102,E110,E133,E160b,E160c,Anticaking E341,E551.'
me = 'Salt,cereal [wheat flour (gluten - triticum aestivum),maize],spices & herbs (irradiated),preservative (sodium sulphite [E221] - yield max 1.40% SO2),MSG (flavour enhancer),[E621],spice extracts,flavour enhancer [E635],flavourings.'
ne = 'SALT HERBS & HERB EXTRACTS SPICES & SPICE EXTRACTS WHEAT FLOUR DEXTROSE FLAVOUR ENHANCER E621 PRESERVATIVE E223 ANTI-OXIDANT E301'
oe = 'Sugar,Glucose syrup,Water,Jelly: pectin,Acidulant: citric acid,malic acid; Flavours,Dyestuffs: Orange: E110,Lemon: E102,Strawberry and Cherry: E120.'
pe = 'triple filtered purified water,vegetable fiber,salt,xanthan gum (thickener),sweetener: sucralose,cellulose gel (thickener),sodium acid sulfate (acidity regulator),caramel color,caramel flavor (4%),preservative: potassium sorbate,sodium benzoate,vanilla flavor,beta carotene,E102,E110 & E129'
econtain_str = [ae,be,fe,ie,je,ke,le,me,ne,oe,pe, g]
all_strings = [d,e,g,h,ae,be,fe,ie,je,ke,le,me,ne,oe,pe]
edeffect = 'El60a, E13l1, E7l33, E4l4k, E456l, E90l,E32l4, E9l3  El62, El532, £245'



start = time.time()
all_wordlists = []
all_long_strings = []
all_enum = []
for string in econtain_str:
    print('input:\n', string)
    test = TextPostprocessing('eng', string)
    print(f'output:\n {test.wordlist}\nFinded E chemicals:\n {test.enums}')
    all_wordlists.extend(test.wordlist)
    all_long_strings.extend(test.longstrings)
    all_enum.extend(test.enums)

    print('_'*100)
end = time.time()
print(f'ALL TEXTS:\n {all_wordlists}')
print(f'ALL E NUMBERS:\n {all_enum}')
print(f'ALL LONG STRINGS:\n {all_long_strings}')
print(f'\nWords total: {len(all_wordlists)}, \nEnums total: {len(all_enum)}, \nLong string total: {len(all_long_strings)}')

print('Время выполнения {} сек'.format(start-end))
