# Generated by Django 3.2 on 2021-05-04 15:18

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.AddIndex(
            model_name='ingredients',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='e_number_data_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='colour_index_data_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='eng_synonyms_data_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['main_name'], name='main_name_btree_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredients',
            index=django.contrib.postgres.indexes.GinIndex(fields=['main_name'], name='trgm_main_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
